In [1]:
print("hello world")

hello world


In [2]:
12+3

15

In [3]:
x = 1

In [4]:
x

1

In [5]:
type(x)

int

In [6]:
y = 1.0

In [7]:
y

1.0

In [8]:
type(y)

float

In [9]:
s = "abc123"

In [10]:
s

'abc123'

In [11]:
type(s)

str

### 데이터 타입예제

In [12]:
x = ['a','b','c','d']
x

['a', 'b', 'c', 'd']

In [13]:
x[0]

'a'

In [14]:
x[-1]

'd'

In [15]:
x[1:-1]

['b', 'c']

In [16]:
x[:3]

['a', 'b', 'c']

In [17]:
x[-2:]

['c', 'd']

In [19]:
z = {1:"apple", 2:"banana"}
z

{1: 'apple', 2: 'banana'}

In [22]:
z[3]

KeyError: 3

In [26]:
z.get(3,"not found")

'not found'

### Function & Module

In [27]:
2**3

8

In [28]:
pow(2,3)

8

In [29]:
int(12.3)

12

In [30]:
int(-4.11)

-4

In [31]:
float(1)

1.0

In [32]:
input("숫자를 넣으세요")

숫자를 넣으세요10


'10'

In [34]:
import math
math.floor(12.3)

12

In [35]:
from math import floor

In [36]:
floor(12.3)

12

In [37]:
import tensorflow as tf

In [38]:
tf.__version__

'2.0.0'

In [39]:
var = 10 

if var < 20:
    print("20보다 작다")
else:
    print("작지않다")

20보다 작다


In [40]:
words = ["this","is","wonder"]

In [42]:
for x in words:
    print(x, end=" ")

this is wonder 

In [47]:
for y in range(1,1000):
    print(y, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 

In [48]:
a = 0 
while True:
    if a > 10:
        break
    a = a + 1
    print(a)

1
2
3
4
5
6
7
8
9
10
11


### 함수 

In [52]:
def getName():
    print("hjkim")

In [53]:
getName()

hjkim


In [54]:
def getNameAge(age):
    print("hjkim", age)

In [55]:
getNameAge(22)

hjkim 22


In [56]:
def add(a, b):
    return a + b

In [57]:
add(10,20)

30

In [58]:
(lambda a,b: a+b)(10,20)

30

### Generator

In [61]:
def gen(n):
    i=0 
    while i < n:
        yield i
        i += 1       

In [62]:
for x in gen(5):
    print(x)

0
1
2
3
4


In [63]:
for x in gen(3):
    print(x)

0
1
2


In [64]:
f = open('some.txt','w')
f.write('hello')
f.close()

In [65]:
f = open('some.txt','r')
f.read()

'hello'

In [66]:
f.close()

In [68]:
try:
    4/0
except ZeroDivisionError as e:
    print(e)

division by zero


### numpy example

In [69]:
import numpy as np

In [71]:
data = {i:np.random.randn() for i in range(7)}
data

{0: -1.248497143427466,
 1: -0.20287417683982564,
 2: -0.38098252988291553,
 3: -1.588766164473466,
 4: -0.01844997926509193,
 5: 1.5194591600523522,
 6: 0.5481784118580223}

In [72]:
from numpy.random import randn

In [73]:
data = {i:randn() for i in range(7)}
data

{0: -0.33025998094223064,
 1: -1.495604042275395,
 2: -1.4917433678593928,
 3: 1.806766422569115,
 4: 0.10355932430293376,
 5: 1.4719776845010573,
 6: -0.15121755122146366}

In [75]:
import numpy as np 

a = np.array([1,2,3])
a

array([1, 2, 3])

In [76]:
type(a)

numpy.ndarray

In [78]:
a[0],a[1],a[2]

(1, 2, 3)

In [79]:
a[0] =5

In [80]:
a

array([5, 2, 3])

In [81]:
a.shape

(3,)

In [82]:
a.ndim

1

In [83]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
b.shape

(2, 3)

In [86]:
np.arange(32).reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [87]:
x = np.array([1,2])
x

array([1, 2])

In [88]:
x.dtype

dtype('int32')

In [89]:
x = np.array([1.,2.])
x.dtype

dtype('float64')

In [90]:
x = np.array([1.,2.], dtype=np.int64)
x.dtype

dtype('int64')

### Tensorflow exam

In [92]:
import tensorflow as tf 

tf.executing_eagerly()

True

In [93]:
x = [[2.]]
m = tf.matmul(x, x)
print("hello, {}".format(m))

hello, [[4.]]


In [94]:
type(m)

tensorflow.python.framework.ops.EagerTensor

In [95]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [96]:
# 브로드캐스팅(Broadcasting) 지원
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [97]:
# NumPy값 사용
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [98]:
# 텐서로부터 numpy 값 얻기:
print(a.numpy())
# => [[1 2]
#     [3 4]]

[[1 2]
 [3 4]]


In [99]:
a

<tf.Tensor: id=7, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [100]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
  loss = w * w

grad = tape.gradient(loss, w)
print(grad)  # => tf.Tensor([[ 2.]], shape=(1, 1), dtype=float32)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)
